# Generated by Django 4.2.17 on 2024-12-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='active_sectors',
            field=models.PositiveIntegerField(default=0, verbose_name='Aktiv sektor sayı'),
        ),
        migrations.AddField(
            model_name='region',
            name='average_attendance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Orta davamiyyət'),
        ),
        migrations.AddField(
            model_name='region',
            name='average_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Orta qiymət'),
        ),
        migrations.AddField(
            model_name='region',
            name='last_report_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son hesabat tarixi'),
        ),
        migrations.AddField(
            model_name='region',
            name='report_status',
            field=models.CharField(choices=[('PENDING', 'Gözləyir'), ('SUBMITTED', 'Təqdim edilib'), ('APPROVED', 'Təsdiqlənib'), ('REJECTED', 'Rədd edilib')], default='PENDING', max_length=20, verbose_name='Hesabat statusu'),
        ),
        migrations.AddField(
            model_name='region',
            name='total_sectors',
            field=models.PositiveIntegerField(default=0, verbose_name='Sektor sayı'),
        ),
    ]
