# Generated by Django 4.2.17 on 2024-12-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_grade_grade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='average_attendance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Orta davamiyyət'),
        ),
        migrations.AddField(
            model_name='school',
            name='average_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Orta qiymət'),
        ),
        migrations.AddField(
            model_name='school',
            name='last_attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Son davamiyyət tarixi'),
        ),
        migrations.AddField(
            model_name='school',
            name='last_grade_date',
            field=models.DateField(blank=True, null=True, verbose_name='Son qiymətləndirmə tarixi'),
        ),
        migrations.AddField(
            model_name='school',
            name='last_report_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son hesabat tarixi'),
        ),
        migrations.AddField(
            model_name='school',
            name='report_status',
            field=models.CharField(choices=[('PENDING', 'Gözləyir'), ('SUBMITTED', 'Təqdim edilib'), ('APPROVED', 'Təsdiqlənib'), ('REJECTED', 'Rədd edilib')], default='PENDING', max_length=20, verbose_name='Hesabat statusu'),
        ),
    ]
