# Generated by Django 4.2.17 on 2024-12-19 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sektor adı')),
                ('utis_code', models.CharField(max_length=7, unique=True, verbose_name='UTIS kodu')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Əlaqə nömrəsi')),
                ('address', models.TextField(verbose_name='Ünvan')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('total_schools', models.PositiveIntegerField(default=0, verbose_name='Məktəb sayı')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Şagird sayı')),
                ('total_teachers', models.PositiveIntegerField(default=0, verbose_name='Müəllim sayı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_sector', to=settings.AUTH_USER_MODEL, verbose_name='Sektor rəhbəri')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='region.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Sektor',
                'verbose_name_plural': 'Sektorlar',
                'ordering': ['region', 'name'],
                'unique_together': {('region', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SectorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('report_type', models.CharField(choices=[('MONTHLY', 'Aylıq'), ('QUARTERLY', 'Rüblük'), ('YEARLY', 'İllik'), ('SPECIAL', 'Xüsusi')], max_length=10, verbose_name='Hesabat növü')),
                ('report_period', models.DateField(verbose_name='Hesabat dövrü')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('status', models.CharField(choices=[('DRAFT', 'Qaralama'), ('PENDING', 'Təsdiq gözləyir'), ('APPROVED', 'Təsdiqlənib'), ('REJECTED', 'Rədd edilib')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('attachments', models.FileField(blank=True, upload_to='sector_reports/', verbose_name='Əlavə fayllar')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Təsdiq tarixi')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rədd səbəbi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL, verbose_name='Təsdiq edən')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='sector.sector', verbose_name='Sektor')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='Təqdim edən')),
            ],
            options={
                'verbose_name': 'Sektor hesabatı',
                'verbose_name_plural': 'Sektor hesabatları',
                'ordering': ['-report_period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectorNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('image', models.ImageField(blank=True, upload_to='sector_news/', verbose_name='Şəkil')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Dərc tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dərc edən')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='sector.sector', verbose_name='Sektor')),
            ],
            options={
                'verbose_name': 'Sektor xəbəri',
                'verbose_name_plural': 'Sektor xəbərləri',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SectorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('document_type', models.CharField(choices=[('REPORT', 'Hesabat'), ('PLAN', 'Plan'), ('ORDER', 'Əmr'), ('OTHER', 'Digər')], max_length=10, verbose_name='Sənəd növü')),
                ('file', models.FileField(upload_to='sector_documents/', verbose_name='Fayl')),
                ('description', models.TextField(blank=True, verbose_name='Açıqlama')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklənmə tarixi')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sector.sector', verbose_name='Sektor')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yükləyən')),
            ],
            options={
                'verbose_name': 'Sektor sənədi',
                'verbose_name_plural': 'Sektor sənədləri',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
