# Generated by Django 4.2.17 on 2024-12-19 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarix')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Köhnə data')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Yeni data')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Dəyişiklik tarixçəsi',
                'verbose_name_plural': 'Dəyişiklik tarixçəsi',
                'ordering': ['-timestamp'],
            },
        ),
    ]
