# Generated by Django 4.2.17 on 2024-12-22 04:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_school_average_attendance_school_average_grade_and_more'),
        ('sector', '0002_sector_average_attendance_sector_average_grade_and_more'),
        ('region', '0002_region_active_sectors_region_average_attendance_and_more'),
        ('core', '0003_customuser_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_admins', to='region.region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_admins', to='sector.sector', verbose_name='Sektor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_admins', to='school.school', verbose_name='Məktəb'),
        ),
    ]
